SYSTEM_CORE=(
    sway
    swaybg
    swaylock
    swayidle
    waybar
    xorg-xwayland
    ly
)

SYSTEM_UTILS=(
    7zip
    zip
    unzip
    bluez
    bluez-utils
    pipewire
    pipewire-alsa
    pipewire-jack
    pipewire-pulse
    gst-plugin-pipewire
    libpulse
    wireplumber
    man-db
    man-pages
    imagemagick
    poppler
    ntfs-3g
    ffmpeg
    resvg
    cups
    trash-cli
    logrotate
    ufw
    net-tools
    nmap
    reflector
    mako
    dmidecode
    dnsmasq
    fastfetch
    nemo
    nemo-fileroller
    libnotify
    jq
    snap-pac
    xdg-user-dirs
    udisks2
    cliphist
    wl-clipboard
    polkit-gnome
    gnome-keyring
    blueman
    xdg-desktop-portal
    xdg-desktop-portal-wlr 
    imv 
    inetutils
    fuzzel 
    make
    avahi
    gvfs
    gvfs-mtp
    gvfs-nfs
    gvfs-afc
    gvfs-smb
    iwd
    wireless_tools
    networkmanager
    wpa_supplicant
    smartmontools
    xdg-utils
    wmenu
    brightnessctl
    grim
    slurp
    btrfs-progs
)

DEV_TOOLS=(
    fd
    fzf
    bat
    less
    ripgrep
    tree
    zoxide
    plocate
    yazi
    github-cli
    neovim
    vim
    starship
    pyright
    bash-language-server
    docker
    docker-compose
    stow
    openssh
    htop
    wget
    curl
    foot
)

VIRTUAL_MACHINE=(
    qemu-desktop
    libvirt
    virt-manager
)

MAINTENANCE=(
    pacman-contrib
)

DESKTOP=(
    libreoffice-still
    chromium
    firefox
    thunderbird
    solaar
)

MEDIA=(
    mpv
    wiremix
)

FONTS=(
    ttf-iosevka-nerd
    ttf-cascadia-mono-nerd
    ttf-firacode-nerd
    noto-fonts 
    noto-fonts-emoji
    otf-ipafont
)

SERVICES=(
    NetworkManager
    ly
    ufw
    systemd-resolved
    systemd-timesyncd
    bluetooth
    paccache.timer
    cups
    avahi-daemon
    logrotate
    libvirtd
)
