SYSTEM_UTILS=(
    7zip
    zip
    unzip
    man-db
    man-pages
    imagemagick
    poppler
    ntfs-3g
    ffmpeg
    resvg
    cups
    trash-cli
    logrotate
    ufw
    nmap
    reflector
    mako
    dmidecode
    dnsmasq
    fastfetch
    nemo
    nemo-fileroller
    libnotify
    jq
    snap-pac
    xdg-user-dirs
    udisks2
    cliphist
    nwg-look
    wl-clipboard
    polkit-gnome
    gnome-keyring
    blueman
    xdg-desktop-portal
    xdg-desktop-portal-wlr
    imv
    fuzzel
    make
    avahi
    gvfs
    gvfs-mtp
    gvfs-nfs
    gvfs-afc
    gvfs-smb
)

DEV_TOOLS=(
    fd
    fzf
    bat
    less
    ripgrep
    tree
    zoxide
    plocate
    yazi
    github-cli
    neovim
    luarocks
    pyright
    clang
    bash-language-server
    lua-language-server
    docker
    docker-compose
    stow
)

VIRTUAL_MACHINE=(
    qemu-desktop
    libvirt
    virt-manager
)

MAINTENANCE=(
    pacman-contrib
)

DESKTOP=(
    libreoffice-still
    chromium
    firefox
    thunderbird
    solaar
)

MEDIA=(
    mpv
    wiremix
)

FONTS=(
    ttc-iosevka
    ttf-nerd-fonts-symbols
    noto-fonts
    noto-fonts-emoji
)

SERVICES=(
    ufw
    systemd-resolved
    systemd-timesyncd
    bluetooth
    paccache.timer
    cups
    avahi-daemon
    logrotate
    libvirtd
    smartd
)
